services:
  - type: web
    name: bayes
    runtime: static
    buildCommand: pnpm run build
    staticPublishPath: ./.svelte-kit
    pullRequestPreviewsEnabled: true
    domains:
      - bayes.nathanarthur.com
